# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/default-symbols-list/
Accept: application/json

###

GET http://127.0.0.1:8000/search/by-symbol/MSFT/
Accept: application/json

###

GET http://127.0.0.1:8000/history/by-symbol/MSFT/?period=1y
Accept: application/json

###